<x-filament-panels::page>
<x-filament-panels::form>
    {{$this->form}}
    <x-filament-panels::form.actions
        alignment="right"
        :actions="$this->getActions()"
    />
</x-filament-panels::form>
</x-filament-panels::page>
